# Generated by Django 2.1.7 on 2019-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190430_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upgradeDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
    ]
