# Generated by Django 2.1.7 on 2019-06-08 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='active',
            field=models.BooleanField(verbose_name='Wazność'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kod kupona'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Zniżka'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Ważność od'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Ważność do'),
        ),
    ]
