# Generated by Django 2.2.2 on 2019-06-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_auto_20190522_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Adres')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kod potcztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Dodany')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aktualizacja')),
                ('paid', models.BooleanField(default=False, verbose_name='Opłacony')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilosć')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='category.Product')),
            ],
        ),
    ]
